### ISSUE TITLE
Unable to compile with fmt 10.0.0

### ISSUE THREAD

**Issue by FtZPetruska** [sandialabs/seacas#382]
## Description

When building with fmt 10.0.0, compilation fails with the following error:

```
D:\installed\x64-windows\include\fmt\core.h(1691): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'
D:\installed\x64-windows\include\fmt\core.h(1711): note: see reference to function template instantiation 'fmt::v10::detail::value<Context> fmt::v10::detail::make_value<Context,Ioss::EntityType&>(T)' being compiled
        with
        [
            Context=fmt::v10::format_context,
            T=Ioss::EntityType &
        ]
```

This is most likely due to the following change made in 10.0.0:
```
Removed deprecated implicit conversions for enums and conversions to primitive types for compatibility with std::format and to prevent potential ODR violations. Use format_as instead.
```

A possible fix is to add for every enum an overload of the `format_as` function, as such:
```cpp
#include <fmt/format.h>

namespace MyNamespace {
enum class Foo {
  BAR = 0
};
auto format_as(Foo f) { return fmt::underlying(f); }
}
```

---

See:
- https://fmt.dev/latest/api.html#formatting-user-defined-types
- https://github.com/fmtlib/fmt/releases/tag/10.0.0
- https://github.com/microsoft/vcpkg/pull/31378

**Comment by gsjaardema** [comment]
Do you have the latest master branch of SEACAS?  I fixed that error yesterday a few hours after 10.0.0 was released...  See 5a576de57ee1664d845c83f552f2100cc9303a26

**Comment by FtZPetruska** [comment]
Thank you for the quick reply, your patch works wonder, thank you!
